### PR TITLE
Fix #673 via checking bound_range properly

### LINKED ISSUE #673: heap-buffer-overflow in ReadUInt8
###### IoT.js version:

```
Checked revision: 20cce20
Build command: ./tools/build.py --buildtype=debug --target-arch=i686 --compile-flag=-fsanitize=address --compile-flag=-fno-omit-frame-pointer --compile-flag=-fno-common --jerry-cmake-param=-DJERRY_LIBC=OFF --jerry-cmake-param=-DFEATURE_SYSTEM_ALLOCATOR=ON --no-snapshot --no-check-valgrind
```
###### OS:

```
Ubuntu 16.04.2 LTS
```
###### Test case:

```javascript
(new Buffer("aaa")).slice(0, 1).readUInt16LE({}, true);
```

###### Backtrace:

```
=================================================================
==28332==ERROR: AddressSanitizer: heap-buffer-overflow on address 0xf5d30c31 at pc 0x08080c59 bp 0xff8b8108 sp 0xff8b80f8
READ of size 1 at 0xf5d30c31 thread T0
    #0 0x8080c58 in ReadUInt8 iotjs/src/module/iotjs_module_buffer.c:380
    #1 0x8067984 in iotjs_native_dispatch_function iotjs/src/iotjs_binding.c:777
    #2 0x8094236 in jerry_dispatch_external_function iotjs/deps/jerry/jerry-core/jerry.c:2065
    #3 0x80e732d in ecma_op_function_call iotjs/deps/jerry/jerry-core/ecma/operations/ecma-function-object.c:543
    #4 0x8122370 in opfunc_call iotjs/deps/jerry/jerry-core/vm/vm.c:391
    #5 0x812c532 in vm_execute iotjs/deps/jerry/jerry-core/vm/vm.c:2661
    #6 0x812cac8 in vm_run iotjs/deps/jerry/jerry-core/vm/vm.c:2740
    #7 0x80e7291 in ecma_op_function_call iotjs/deps/jerry/jerry-core/ecma/operations/ecma-function-object.c:524
    #8 0x8122370 in opfunc_call iotjs/deps/jerry/jerry-core/vm/vm.c:391
    #9 0x812c532 in vm_execute iotjs/deps/jerry/jerry-core/vm/vm.c:2661
    #10 0x812cac8 in vm_run iotjs/deps/jerry/jerry-core/vm/vm.c:2740
    #11 0x80e7291 in ecma_op_function_call iotjs/deps/jerry/jerry-core/ecma/operations/ecma-function-object.c:524
    #12 0x8135803 in ecma_builtin_function_prototype_object_call iotjs/deps/jerry/jerry-core/ecma/builtin-objects/ecma-builtin-function-prototype.c:206
    #13 0x8135158 in ecma_builtin_function_prototype_dispatch_routine iotjs/deps/jerry/jerry-core/ecma/builtin-objects/ecma-builtin-function-prototype.inc.h:51
    #14 0x80b5a1b in ecma_builtin_dispatch_routine iotjs/deps/jerry/jerry-core/ecma/builtin-objects/ecma-builtins.inc.h:108
    #15 0x80b5fcd in ecma_builtin_dispatch_call iotjs/deps/jerry/jerry-core/ecma/builtin-objects/ecma-builtins.c:844
    #16 0x80e7066 in ecma_op_function_call iotjs/deps/jerry/jerry-core/ecma/operations/ecma-function-object.c:461
    #17 0x8122370 in opfunc_call iotjs/deps/jerry/jerry-core/vm/vm.c:391
    #18 0x812c532 in vm_execute iotjs/deps/jerry/jerry-core/vm/vm.c:2661
    #19 0x812cac8 in vm_run iotjs/deps/jerry/jerry-core/vm/vm.c:2740
    #20 0x80e7291 in ecma_op_function_call iotjs/deps/jerry/jerry-core/ecma/operations/ecma-function-object.c:524
    #21 0x8122370 in opfunc_call iotjs/deps/jerry/jerry-core/vm/vm.c:391
    #22 0x812c532 in vm_execute iotjs/deps/jerry/jerry-core/vm/vm.c:2661
    #23 0x812cac8 in vm_run iotjs/deps/jerry/jerry-core/vm/vm.c:2740
    #24 0x80e7291 in ecma_op_function_call iotjs/deps/jerry/jerry-core/ecma/operations/ecma-function-object.c:524
    #25 0x8122370 in opfunc_call iotjs/deps/jerry/jerry-core/vm/vm.c:391
    #26 0x812c532 in vm_execute iotjs/deps/jerry/jerry-core/vm/vm.c:2661
    #27 0x812cac8 in vm_run iotjs/deps/jerry/jerry-core/vm/vm.c:2740
    #28 0x80e7291 in ecma_op_function_call iotjs/deps/jerry/jerry-core/ecma/operations/ecma-function-object.c:524
    #29 0x8122370 in opfunc_call iotjs/deps/jerry/jerry-core/vm/vm.c:391
    #30 0x812c532 in vm_execute iotjs/deps/jerry/jerry-core/vm/vm.c:2661
    #31 0x812cac8 in vm_run iotjs/deps/jerry/jerry-core/vm/vm.c:2740
    #32 0x80e7291 in ecma_op_function_call iotjs/deps/jerry/jerry-core/ecma/operations/ecma-function-object.c:524
    #33 0x8122370 in opfunc_call iotjs/deps/jerry/jerry-core/vm/vm.c:391
    #34 0x812c532 in vm_execute iotjs/deps/jerry/jerry-core/vm/vm.c:2661
    #35 0x812cac8 in vm_run iotjs/deps/jerry/jerry-core/vm/vm.c:2740
    #36 0x80e7291 in ecma_op_function_call iotjs/deps/jerry/jerry-core/ecma/operations/ecma-function-object.c:524
    #37 0x80936e5 in jerry_invoke_function iotjs/deps/jerry/jerry-core/jerry.c:1766
    #38 0x809378d in jerry_call_function iotjs/deps/jerry/jerry-core/jerry.c:1792
    #39 0x80620ba in iotjs_jhelper_call iotjs/src/iotjs_binding.c:430
    #40 0x805a028 in iotjs_run iotjs/src/iotjs.c:98
    #41 0x805a1e8 in iotjs_start iotjs/src/iotjs.c:131
    #42 0x805a695 in iotjs_entry iotjs/src/iotjs.c:191
    #43 0x8059995 in main iotjs/iotjs_linux.c:19
    #44 0xf7022636 in __libc_start_main (/lib/i386-linux-gnu/libc.so.6+0x18636)
    #45 0x80598a0  (iotjs/build/i686-linux/debug/bin/_iotjs+0x80598a0)

0xf5d30c31 is located 0 bytes to the right of 1-byte region [0xf5d30c30,0xf5d30c31)
allocated by thread T0 here:
    #0 0xf72c8f8e in calloc (/usr/lib32/libasan.so.2+0x96f8e)
    #1 0x808c737 in iotjs_buffer_allocate iotjs/src/iotjs_util.c:61
    #2 0x807c73f in iotjs_bufferwrap_create iotjs/src/module/iotjs_module_buffer.c:34
    #3 0x807ec5c in Buffer iotjs/src/module/iotjs_module_buffer.c:229
    #4 0x8067984 in iotjs_native_dispatch_function iotjs/src/iotjs_binding.c:777
    #5 0x8094236 in jerry_dispatch_external_function iotjs/deps/jerry/jerry-core/jerry.c:2065
    #6 0x80e732d in ecma_op_function_call iotjs/deps/jerry/jerry-core/ecma/operations/ecma-function-object.c:543
    #7 0x80e7802 in ecma_op_function_construct_simple_or_external iotjs/deps/jerry/jerry-core/ecma/operations/ecma-function-object.c:657
    #8 0x80e79d3 in ecma_op_function_construct iotjs/deps/jerry/jerry-core/ecma/operations/ecma-function-object.c:725
    #9 0x81227c1 in opfunc_construct iotjs/deps/jerry/jerry-core/vm/vm.c:449
    #10 0x812c5af in vm_execute iotjs/deps/jerry/jerry-core/vm/vm.c:2666
    #11 0x812cac8 in vm_run iotjs/deps/jerry/jerry-core/vm/vm.c:2740
    #12 0x80e7291 in ecma_op_function_call iotjs/deps/jerry/jerry-core/ecma/operations/ecma-function-object.c:524
    #13 0x80e7802 in ecma_op_function_construct_simple_or_external iotjs/deps/jerry/jerry-core/ecma/operations/ecma-function-object.c:657
    #14 0x80e79a2 in ecma_op_function_construct iotjs/deps/jerry/jerry-core/ecma/operations/ecma-function-object.c:718
    #15 0x81227c1 in opfunc_construct iotjs/deps/jerry/jerry-core/vm/vm.c:449
    #16 0x812c5af in vm_execute iotjs/deps/jerry/jerry-core/vm/vm.c:2666
    #17 0x812cac8 in vm_run iotjs/deps/jerry/jerry-core/vm/vm.c:2740
    #18 0x80e7291 in ecma_op_function_call iotjs/deps/jerry/jerry-core/ecma/operations/ecma-function-object.c:524
    #19 0x80936e5 in jerry_invoke_function iotjs/deps/jerry/jerry-core/jerry.c:1766
    #20 0x809378d in jerry_call_function iotjs/deps/jerry/jerry-core/jerry.c:1792
    #21 0x80620ba in iotjs_jhelper_call iotjs/src/iotjs_binding.c:430
    #22 0x80622a1 in iotjs_jhelper_call_ok iotjs/src/iotjs_binding.c:450
    #23 0x807e73f in iotjs_bufferwrap_create_buffer iotjs/src/module/iotjs_module_buffer.c:208
    #24 0x808117e in Slice iotjs/src/module/iotjs_module_buffer.c:410
    #25 0x8067984 in iotjs_native_dispatch_function iotjs/src/iotjs_binding.c:777
    #26 0x8094236 in jerry_dispatch_external_function iotjs/deps/jerry/jerry-core/jerry.c:2065
    #27 0x80e732d in ecma_op_function_call iotjs/deps/jerry/jerry-core/ecma/operations/ecma-function-object.c:543
    #28 0x8122370 in opfunc_call iotjs/deps/jerry/jerry-core/vm/vm.c:391
    #29 0x812c532 in vm_execute iotjs/deps/jerry/jerry-core/vm/vm.c:2661

SUMMARY: AddressSanitizer: heap-buffer-overflow iotjs/src/module/iotjs_module_buffer.c:380 ReadUInt8
Shadow bytes around the buggy address:
  0x3eba6130: fa fa fd fa fa fa fd fa fa fa fd fd fa fa fd fa
  0x3eba6140: fa fa fd fd fa fa fd fa fa fa fd fa fa fa fd fa
  0x3eba6150: fa fa fd fa fa fa fd fa fa fa 00 00 fa fa 00 00
  0x3eba6160: fa fa fd fa fa fa 00 00 fa fa fd fa fa fa 00 00
  0x3eba6170: fa fa 00 00 fa fa fd fa fa fa fd fa fa fa fd fd
=>0x3eba6180: fa fa fd fa fa fa[01]fa fa fa 04 fa fa fa 04 fa
  0x3eba6190: fa fa 00 07 fa fa fd fa fa fa fd fa fa fa fd fa
  0x3eba61a0: fa fa fd fa fa fa fd fa fa fa fd fa fa fa 00 00
  0x3eba61b0: fa fa fd fa fa fa fd fa fa fa 00 00 fa fa fd fa
  0x3eba61c0: fa fa fd fd fa fa fd fa fa fa fd fa fa fa fd fd
  0x3eba61d0: fa fa fd fa fa fa fd fa fa fa fd fd fa fa fd fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
==28332==ABORTING
```

<sup>Found by  [Fuzzinator](http://fuzzinator.readthedocs.io/)</sup>

### PR DESCRIPTION
**Pull request by daeyeon**
This commit fixes the buffer over-read error in ReadUInt8.

IoT.js-DCO-1.0-Signed-off-by: Daeyeon Jeong daeyeon.jeong@samsung.com

### CODE REVIEW

**Comment by yichoi** [comment]
Please add testcase for this patch

File: test/run_pass/test_buffer.js [hunk 1]
```diff
@@ -141,3 +141,4 @@ assert.equal(buff16.readInt8(2), 13);
 assert.equal(buff16.readInt8(3), 13);
 
 assert.equal(Buffer(new Array()).toString(),'');
+assert.equal(new Buffer(1).readUInt16LE({}, true),0);
```
Comment (hs0225) [inline test/run_pass/test_buffer.js]: I think the correct test case is that `offset` is `1`.

Comment (daeyeon) [inline test/run_pass/test_buffer.js]: I added a test case for readUInt8, which is called inside readUInt16LE with offset, -1. Thank you.

**Comment by yichoi** [comment]
LGTM
