### PR TITLE
Fix setting exit code

### LINKED ISSUE #1570: Assertion '!jerry_value_has_error_flag(ret_val)' failed in iotjs_jval_set_property_jval
###### IoT.js version:

```
Checked revision: cc08854
Build command: ./tools/build.py --clean --buildtype=debug --jerry-profile=es2015-subset
```
###### OS:

```
Ubuntu 17.10, x86_64
```
###### Test case:

```javascript
var dns = require('dns');
dns.lookup("127.0.0.1", Object.setPrototypeOf, Object.freeze(process, Int32Array))
```

###### Backtrace:

```
uncaughtException: TypeError: Argument cannot be converted to an object.
iotjs/src/iotjs_binding.c:155: Assertion '!jerry_value_has_error_flag(ret_val)' failed.

[Backtrace]:
iotjs/src/iotjs_util.c:107
iotjs/src/iotjs_binding.c:155 (discriminator 1)
iotjs/src/iotjs_binding.c:180
iotjs/src/iotjs_binding_helper.c:162
iotjs/src/modules/iotjs_module_process.c:229
iotjs/deps/jerry/jerry-core/ecma/operations/ecma-function-object.c:559
iotjs/deps/jerry/jerry-core/vm/vm.c:441
iotjs/deps/jerry/jerry-core/vm/vm.c:2912
iotjs/deps/jerry/jerry-core/vm/vm.c:2985 (discriminator 3)
iotjs/deps/jerry/jerry-core/ecma/operations/ecma-function-object.c:500
iotjs/deps/jerry/jerry-core/vm/vm.c:441
iotjs/deps/jerry/jerry-core/vm/vm.c:2912
iotjs/deps/jerry/jerry-core/vm/vm.c:2985 (discriminator 3)
iotjs/deps/jerry/jerry-core/ecma/operations/ecma-function-object.c:500
iotjs/deps/jerry/jerry-core/api/jerry.c:2254
iotjs/deps/jerry/jerry-core/api/jerry.c:2280
iotjs/src/iotjs_binding.c:258
iotjs/src/iotjs_binding_helper.c:33
iotjs/src/iotjs_binding_helper.c:129
iotjs/src/iotjs_binding_helper.c:111
iotjs/src/modules/iotjs_module_dns.c:145
iotjs/deps/libtuv/src/unix/getaddrinfo.c:157
iotjs/deps/libtuv/src/threadpool.c:255 (discriminator 1)
iotjs/deps/libtuv/src/unix/async.c:110 (discriminator 1)
iotjs/deps/libtuv/src/unix/async.c:163
iotjs/deps/libtuv/src/unix/linux-core.c:391
iotjs/deps/libtuv/src/unix/core.c:306
iotjs/src/iotjs.c:141
iotjs/src/iotjs.c:207
iotjs/src/platform/linux/iotjs_linux.c:20
```

<sup>Found by [Fuzzinator](http://fuzzinator.readthedocs.io/)</sup>

### PR DESCRIPTION
**Pull request by DanielBallaSZTE**
The success of setting the exitcode property on exiting shouldn't be checked, since the property could be inaccessible for any reason.
Therefore, set it manually without the `iotjs_jval_set_property` function, and just release the return value.

Fixes #1570

IoT.js-DCO-1.0-Signed-off-by: Daniel Balla dballa@inf.u-szeged.hu

### CODE REVIEW

File: src/iotjs_binding_helper.c [hunk 1]
```diff
@@ -171,5 +171,12 @@ int iotjs_process_exitcode() {
 
 void iotjs_set_process_exitcode(int code) {
   const jerry_value_t process = iotjs_module_get("process");
-  iotjs_jval_set_property_number(process, IOTJS_MAGIC_STRING_EXITCODE, code);
+  jerry_value_t jstring =
+      jerry_create_string((jerry_char_t*)IOTJS_MAGIC_STRING_EXITCODE);
+  jerry_value_t jcode = jerry_create_number(code);
+  jerry_value_t ret_val = jerry_set_property(process, jstring, jcode);
```
Comment (LaszloLango) [inline src/iotjs_binding_helper.c]: A bit shorter way: `jerry_release_value(jerry_set_property(process, jstring, jcode));`

Comment (DanielBallaSZTE) [reply src/iotjs_binding_helper.c]: Yes, it's definitely shorter, but I don't know if it looks better.
However you are right, since the return value would be freed anyway.
