### PR TITLE
Ignore process.exit() calls when process is exiting.

### LINKED ISSUE #1350: Assertion '_this->state < kExiting' failed in iotjs_environment_go_state_exiting
###### IoT.js version:

```
Checked revision: a6b2d75
Build command: tools/build.py --buildtype debug --no-snapshot --no-check-test
```
###### OS:

```
Ubuntu 17.10
```
###### Test case:

```javascript
process.on('exit', function() { process.exit('callback'); } );      
```

###### Backtrace:

```
iotjs/src/iotjs_env.c:214: Assertion '_this->state < kExiting' failed.

(gdb) bt
#0  iotjs_environment_go_state_exiting (env=0x55555584a440 <current_env>) at iotjs/src/iotjs_env.c:214
#1  0x000055555556ca9b in iotjs_start (env=0x55555584a440 <current_env>) at iotjs/src/iotjs.c:166
#2  0x000055555556cce8 in iotjs_entry (argc=2, argv=0x7fffffffdec8) at iotjs/src/iotjs.c:218
#3  0x000055555556c4ca in main (argc=2, argv=0x7fffffffdec8) at iotjs/iotjs_linux.c:19
```

<sup>Found by [Fuzzinator](http://fuzzinator.readthedocs.io/) with [grammarinator](https://github.com/renatahodovan/grammarinator)</sup>

### PR DESCRIPTION
**Pull request by zherczeg**
Fixes #1350.

### CODE REVIEW

File: src/js/iotjs.js [hunk 1]
```diff
@@ -143,19 +143,21 @@
...
 
   process.exit = function(code) {
-    try {
-      process.emitExit(code);
-    } catch (e) {
-      process.exitCode = 1;
-      process._onUncaughtException(e);
-    } finally {
-      process.doExit(process.exitCode || 0);
+    if (!process._exiting) {
```
Comment (galpeter) [inline src/js/iotjs.js]: What if we change the logic?:

```js
if (process._exiting) {
  return;
} 
```

Comment (zherczeg) [reply src/js/iotjs.js]: The nested ifs are used everywhere. But for me this is not relevant. Actually node.js throws an error instead of return.

**Comment by yichoi** [comment]
LGTM
