### PR TITLE
Fix memory leak in setTimeout

### LINKED ISSUE #1353: Memory leak in 'setTimeout' on exceptions
###### IoT.js version:

```
Checked revision: 67b1de3
Build command: tools/build.py --clean
```
###### OS:

```
Ubuntu 16.04
```
###### Test case:

```javascript
setTimeout(function() { throw "error" }, 100);
```

###### Backtrace:

The test case a memory leak.

with x86_64-linux target:

```
==30636== Memcheck, a memory error detector
==30636== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==30636== Using Valgrind-3.11.0 and LibVEX; rerun with -h for copyright info
==30636== Command: ./build/x86_64-linux/debug/bin/iotjs tmp.js
==30636== 
uncaughtException: error
==30636== 
==30636== HEAP SUMMARY:
==30636==     in use at exit: 104 bytes in 1 blocks
==30636==   total heap usage: 41 allocs, 40 frees, 5,257 bytes allocated
==30636== 
==30636== 104 bytes in 1 blocks are definitely lost in loss record 1 of 1
==30636==    at 0x4C2FB55: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==30636==    by 0x41608F: iotjs_buffer_allocate (iotjs_util.c:68)
==30636==    by 0x42586D: iotjs_timerwrap_create (iotjs_module_timer.c:27)
==30636==    by 0x4262FB: Timer (iotjs_module_timer.c:156)
==30636==    by 0x4627BF: ecma_op_function_call (ecma-function-object.c:467)
==30636==    by 0x462BF1: ecma_op_function_construct_simple_or_external (ecma-function-object.c:598)
==30636==    by 0x462DB6: ecma_op_function_construct (ecma-function-object.c:666)
==30636==    by 0x47A7F1: opfunc_construct (vm.c:483)
==30636==    by 0x47F679: vm_execute (vm.c:2798)
==30636==    by 0x47F8BF: vm_run (vm.c:2873)
==30636==    by 0x462747: ecma_op_function_call (ecma-function-object.c:406)
==30636==    by 0x47A6B3: opfunc_call (vm.c:425)
==30636== 
==30636== LEAK SUMMARY:
==30636==    definitely lost: 104 bytes in 1 blocks
==30636==    indirectly lost: 0 bytes in 0 blocks
==30636==      possibly lost: 0 bytes in 0 blocks
==30636==    still reachable: 0 bytes in 0 blocks
==30636==         suppressed: 0 bytes in 0 blocks
==30636== 
==30636== For counts of detected and suppressed errors, rerun with: -v
==30636== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
```

### PR DESCRIPTION
**Pull request by LaszloLango**
Fixes #1353 

IoT.js-DCO-1.0-Signed-off-by: László Langó llango.u-szeged@partner.samsung.com

### CODE REVIEW

File: src/js/timers.js [hunk 1]
```diff
@@ -29,7 +29,13 @@ function Timeout(after) {
 native.prototype.handleTimeout = function() {
   var timeout = this.timeoutObj; // 'this' is native object
   if (timeout && timeout.callback) {
-    timeout.callback();
+    try {
+      timeout.callback();
+    } catch (e) {
+      timeout.unref();
```
Comment (zherczeg) [inline src/js/timers.js]: Don't we need `if (!timeout.isrepeat)` here as well? An exception aborts a periodic timer?

Comment (LaszloLango) [reply src/js/timers.js]: Yes, an exception must abort a periodic timer too.

**Comment by yichoi** [comment]
LGTM
