### PR TITLE
Fixed chain calls of Promise objects which contains async calls.

### LINKED ISSUE #1292: Chain calls cannot be implemented
I want to implement exact chain calls in iotjs. Here are the test cases. Just read several files in chained form. The file name can be modified by itself. This code works normally in nodejs. I opened the es2015-subset. So Promise is available. Parallel code is normally called and serial is not.

```javascript
var fs = require('fs')
function readfile(fileName){
  return new Promise(function (resolve, reject){
    fs.readFile(fileName, function(error, data){
      if (error) reject(error);
        console.log(data.toString());      
        resolve(data);      
    });
  });
};
code ERR:
readfile('test.csv').then(function() {
    readfile('NMap.ts').then(function() {
        readfile('NMap.js').then(function() {
             readfile('test.csv').then(function() {
             console.log(Date.now());
           })
        })
    })
})
code OK:
var tasks=[];
tasks.push(readfile('test.csv'));
tasks.push(readfile('NMap.ts'));
tasks.push(readfile('NMap.js'));
tasks.push(readfile('test.csv'));
Promise.all(tasks).then(function () {
      console.log(new Date());
});
```

### PR DESCRIPTION
**Pull request by LaszloLango**
Fixes #1292 

IoT.js-DCO-1.0-Signed-off-by: László Langó llango.u-szeged@partner.samsung.com

### CODE REVIEW

File: test/run_pass/test_iotjs_promise_chain_calls.js [hunk 1]
```diff
@@ -0,0 +1,58 @@
...
+                 + files[idx];
+
+  readfile(fileName).
+    then(function(value) {
+      assert.equal(value, 'Content of ' + files[idx] + '\n');
+      idx++;
+      loadfi(files, idx);
+    }).catch(function (e) {
+     // Note: assert cannot be used here, because exception cannot be thrown
+     //       from Promise.prototype.catch
```
Comment (galpeter) [inline test/run_pass/test_iotjs_promise_chain_calls.js]: The indentation is off by one in the comments. Is that intentional?

File: test/run_pass/test_iotjs_promise_chain_calls.js [hunk 2]
```diff
@@ -0,0 +1,58 @@
...
+      if (e.message !== "Cannot open file!") {
+        console.log('Error message does not match. Expected '
+                    + '"Cannot open file!", but got "'
+                    + e.message + '".');
+        process.emitExit(1);
+      } else if (idx !== 4) {
+        console.log('Did not read every file. The expected number of files '
+                    + 'read is "4", but got "' + idx + '".');
+        process.emitExit(1);
+      }
```
Comment (galpeter) [inline test/run_pass/test_iotjs_promise_chain_calls.js]: Two questions:
* Should we also check any other reasons for failure?
* Can we hoist the `emitExit` call out of the if-s to the function end? Thus if any error occurs we'll exit.

File: test/run_pass/test_iotjs_promise_chain_calls.js (hunk 1 above)
Comment (LaszloLango) [reply test/run_pass/test_iotjs_promise_chain_calls.js]: No, it is accidental.

File: test/run_pass/test_iotjs_promise_chain_calls.js (hunk 2 above)
Comment (LaszloLango) [reply test/run_pass/test_iotjs_promise_chain_calls.js]: Yes, we should check and the test does it. If any error happens different than the `reject("Cannot  open file.")` it will exit with 1. This will happen, when the test tries to open "`undefined`". I wanted to keep the original behavior of the test.

**Comment by yichoi** [comment]
LGTM
