### PR TITLE
Fix #674 to check if user inputs are valid

### LINKED ISSUE #674: heap-use-after-free in uv__fs_read
###### IoT.js version:

```
Checked revision: 20cce20
Build command: ./tools/build.py --buildtype=debug --target-arch=i686 --compile-flag=-fsanitize=address --compile-flag=-fno-omit-frame-pointer --compile-flag=-fno-common --jerry-cmake-param=-DJERRY_LIBC=OFF --jerry-cmake-param=-DFEATURE_SYSTEM_ALLOCATOR=ON --no-snapshot --no-check-valgrind
```
###### OS:

```
Ubuntu 16.04.2 LTS
```
###### Test case:

```javascript
var fs = require('fs');
var http_client = require('http_client');

fs.readFileSync("/PATH/TO/IOTJS/test/run_pass/attrs.js")
fs.openSync("/PATH/TO/IOTJS/test/run_pass/attrs.js", "r")
fs.readFileSync("/PATH/TO/IOTJS/test/run_pass/attrs.js")
fs.readSync(5, fs.readFileSync("/PATH/TO/IOTJS/test/run_pass/attrs.js"), -1805, 335)
```

`/PATH/TO/IOTJS` has to point to the IoT.js repository.

###### Backtrace:

```
=================================================================
==24507==ERROR: AddressSanitizer: heap-use-after-free on address 0xf21029f3 at pc 0xf725053d bp 0xffd9f778 sp 0xffd9f34c
WRITE of size 3 at 0xf21029f3 thread T0
    #0 0xf725053c  (/usr/lib32/libasan.so.2+0x3f53c)
    #1 0x8153673 in uv__fs_read iotjs/deps/libtuv/src/unix/fs.c:303
    #2 0x8155b02 in uv__fs_buf_iter iotjs/deps/libtuv/src/unix/fs.c:634
    #3 0x8156062 in uv__fs_work iotjs/deps/libtuv/src/unix/fs.c:689
    #4 0x8158afc in uv_fs_read iotjs/deps/libtuv/src/unix/fs.c:836
    #5 0x806d849 in Read iotjs/src/module/iotjs_module_fs.c:271
    #6 0x8067984 in iotjs_native_dispatch_function iotjs/src/iotjs_binding.c:777
    #7 0x8094236 in jerry_dispatch_external_function iotjs/deps/jerry/jerry-core/jerry.c:2065
    #8 0x80e732d in ecma_op_function_call iotjs/deps/jerry/jerry-core/ecma/operations/ecma-function-object.c:543
    #9 0x8122370 in opfunc_call iotjs/deps/jerry/jerry-core/vm/vm.c:391
    #10 0x812c532 in vm_execute iotjs/deps/jerry/jerry-core/vm/vm.c:2661
    #11 0x812cac8 in vm_run iotjs/deps/jerry/jerry-core/vm/vm.c:2740
    #12 0x80e7291 in ecma_op_function_call iotjs/deps/jerry/jerry-core/ecma/operations/ecma-function-object.c:524
    #13 0x8122370 in opfunc_call iotjs/deps/jerry/jerry-core/vm/vm.c:391
    #14 0x812c532 in vm_execute iotjs/deps/jerry/jerry-core/vm/vm.c:2661
    #15 0x812cac8 in vm_run iotjs/deps/jerry/jerry-core/vm/vm.c:2740
    #16 0x80e7291 in ecma_op_function_call iotjs/deps/jerry/jerry-core/ecma/operations/ecma-function-object.c:524
    #17 0x8135803 in ecma_builtin_function_prototype_object_call iotjs/deps/jerry/jerry-core/ecma/builtin-objects/ecma-builtin-function-prototype.c:206
    #18 0x8135158 in ecma_builtin_function_prototype_dispatch_routine iotjs/deps/jerry/jerry-core/ecma/builtin-objects/ecma-builtin-function-prototype.inc.h:51
    #19 0x80b5a1b in ecma_builtin_dispatch_routine iotjs/deps/jerry/jerry-core/ecma/builtin-objects/ecma-builtins.inc.h:108
    #20 0x80b5fcd in ecma_builtin_dispatch_call iotjs/deps/jerry/jerry-core/ecma/builtin-objects/ecma-builtins.c:844
    #21 0x80e7066 in ecma_op_function_call iotjs/deps/jerry/jerry-core/ecma/operations/ecma-function-object.c:461
    #22 0x8122370 in opfunc_call iotjs/deps/jerry/jerry-core/vm/vm.c:391
    #23 0x812c532 in vm_execute iotjs/deps/jerry/jerry-core/vm/vm.c:2661
    #24 0x812cac8 in vm_run iotjs/deps/jerry/jerry-core/vm/vm.c:2740
    #25 0x80e7291 in ecma_op_function_call iotjs/deps/jerry/jerry-core/ecma/operations/ecma-function-object.c:524
    #26 0x8122370 in opfunc_call iotjs/deps/jerry/jerry-core/vm/vm.c:391
    #27 0x812c532 in vm_execute iotjs/deps/jerry/jerry-core/vm/vm.c:2661
    #28 0x812cac8 in vm_run iotjs/deps/jerry/jerry-core/vm/vm.c:2740
    #29 0x80e7291 in ecma_op_function_call iotjs/deps/jerry/jerry-core/ecma/operations/ecma-function-object.c:524
    #30 0x8122370 in opfunc_call iotjs/deps/jerry/jerry-core/vm/vm.c:391
    #31 0x812c532 in vm_execute iotjs/deps/jerry/jerry-core/vm/vm.c:2661
    #32 0x812cac8 in vm_run iotjs/deps/jerry/jerry-core/vm/vm.c:2740
    #33 0x80e7291 in ecma_op_function_call iotjs/deps/jerry/jerry-core/ecma/operations/ecma-function-object.c:524
    #34 0x8122370 in opfunc_call iotjs/deps/jerry/jerry-core/vm/vm.c:391
    #35 0x812c532 in vm_execute iotjs/deps/jerry/jerry-core/vm/vm.c:2661
    #36 0x812cac8 in vm_run iotjs/deps/jerry/jerry-core/vm/vm.c:2740
    #37 0x80e7291 in ecma_op_function_call iotjs/deps/jerry/jerry-core/ecma/operations/ecma-function-object.c:524
    #38 0x8122370 in opfunc_call iotjs/deps/jerry/jerry-core/vm/vm.c:391
    #39 0x812c532 in vm_execute iotjs/deps/jerry/jerry-core/vm/vm.c:2661
    #40 0x812cac8 in vm_run iotjs/deps/jerry/jerry-core/vm/vm.c:2740
    #41 0x80e7291 in ecma_op_function_call iotjs/deps/jerry/jerry-core/ecma/operations/ecma-function-object.c:524
    #42 0x80936e5 in jerry_invoke_function iotjs/deps/jerry/jerry-core/jerry.c:1766
    #43 0x809378d in jerry_call_function iotjs/deps/jerry/jerry-core/jerry.c:1792
    #44 0x80620ba in iotjs_jhelper_call iotjs/src/iotjs_binding.c:430
    #45 0x805a028 in iotjs_run iotjs/src/iotjs.c:98
    #46 0x805a1e8 in iotjs_start iotjs/src/iotjs.c:131
    #47 0x805a695 in iotjs_entry iotjs/src/iotjs.c:191
    #48 0x8059995 in main iotjs/iotjs_linux.c:19
    #49 0xf7001636 in __libc_start_main (/lib/i386-linux-gnu/libc.so.6+0x18636)
    #50 0x80598a0  (iotjs/build/i686-linux/debug/bin/_iotjs+0x80598a0)

0xf21029f3 is located 4339 bytes inside of 5387-byte region [0xf2101900,0xf2102e0b)
freed by thread T0 here:
    #0 0xf72a7a84 in free (/usr/lib32/libasan.so.2+0x96a84)
    #1 0x808c7f7 in iotjs_buffer_release iotjs/src/iotjs_util.c:75
    #2 0x8078505 in WrapEval iotjs/src/module/iotjs_module_process.c:49
    #3 0x8078df7 in CompileNativePtr iotjs/src/module/iotjs_module_process.c:97
    #4 0x8067984 in iotjs_native_dispatch_function iotjs/src/iotjs_binding.c:777
    #5 0x8094236 in jerry_dispatch_external_function iotjs/deps/jerry/jerry-core/jerry.c:2065
    #6 0x80e732d in ecma_op_function_call iotjs/deps/jerry/jerry-core/ecma/operations/ecma-function-object.c:543
    #7 0x8122370 in opfunc_call iotjs/deps/jerry/jerry-core/vm/vm.c:391
    #8 0x812c532 in vm_execute iotjs/deps/jerry/jerry-core/vm/vm.c:2661
    #9 0x812cac8 in vm_run iotjs/deps/jerry/jerry-core/vm/vm.c:2740
    #10 0x80e7291 in ecma_op_function_call iotjs/deps/jerry/jerry-core/ecma/operations/ecma-function-object.c:524
    #11 0x8122370 in opfunc_call iotjs/deps/jerry/jerry-core/vm/vm.c:391
    #12 0x812c532 in vm_execute iotjs/deps/jerry/jerry-core/vm/vm.c:2661
    #13 0x812cac8 in vm_run iotjs/deps/jerry/jerry-core/vm/vm.c:2740
    #14 0x80e7291 in ecma_op_function_call iotjs/deps/jerry/jerry-core/ecma/operations/ecma-function-object.c:524
    #15 0x8122370 in opfunc_call iotjs/deps/jerry/jerry-core/vm/vm.c:391
    #16 0x812c532 in vm_execute iotjs/deps/jerry/jerry-core/vm/vm.c:2661
    #17 0x812cac8 in vm_run iotjs/deps/jerry/jerry-core/vm/vm.c:2740
    #18 0x80e7291 in ecma_op_function_call iotjs/deps/jerry/jerry-core/ecma/operations/ecma-function-object.c:524
    #19 0x8122370 in opfunc_call iotjs/deps/jerry/jerry-core/vm/vm.c:391
    #20 0x812c532 in vm_execute iotjs/deps/jerry/jerry-core/vm/vm.c:2661
    #21 0x812cac8 in vm_run iotjs/deps/jerry/jerry-core/vm/vm.c:2740
    #22 0x80e7291 in ecma_op_function_call iotjs/deps/jerry/jerry-core/ecma/operations/ecma-function-object.c:524
    #23 0x8122370 in opfunc_call iotjs/deps/jerry/jerry-core/vm/vm.c:391
    #24 0x812c532 in vm_execute iotjs/deps/jerry/jerry-core/vm/vm.c:2661
    #25 0x812cac8 in vm_run iotjs/deps/jerry/jerry-core/vm/vm.c:2740
    #26 0x80e7291 in ecma_op_function_call iotjs/deps/jerry/jerry-core/ecma/operations/ecma-function-object.c:524
    #27 0x8122370 in opfunc_call iotjs/deps/jerry/jerry-core/vm/vm.c:391
    #28 0x812c532 in vm_execute iotjs/deps/jerry/jerry-core/vm/vm.c:2661
    #29 0x812cac8 in vm_run iotjs/deps/jerry/jerry-core/vm/vm.c:2740

previously allocated by thread T0 here:
    #0 0xf72a7f8e in calloc (/usr/lib32/libasan.so.2+0x96f8e)
    #1 0x808c737 in iotjs_buffer_allocate iotjs/src/iotjs_util.c:61
    #2 0x807844f in WrapEval iotjs/src/module/iotjs_module_process.c:42
    #3 0x8078df7 in CompileNativePtr iotjs/src/module/iotjs_module_process.c:97
    #4 0x8067984 in iotjs_native_dispatch_function iotjs/src/iotjs_binding.c:777
    #5 0x8094236 in jerry_dispatch_external_function iotjs/deps/jerry/jerry-core/jerry.c:2065
    #6 0x80e732d in ecma_op_function_call iotjs/deps/jerry/jerry-core/ecma/operations/ecma-function-object.c:543
    #7 0x8122370 in opfunc_call iotjs/deps/jerry/jerry-core/vm/vm.c:391
    #8 0x812c532 in vm_execute iotjs/deps/jerry/jerry-core/vm/vm.c:2661
    #9 0x812cac8 in vm_run iotjs/deps/jerry/jerry-core/vm/vm.c:2740
    #10 0x80e7291 in ecma_op_function_call iotjs/deps/jerry/jerry-core/ecma/operations/ecma-function-object.c:524
    #11 0x8122370 in opfunc_call iotjs/deps/jerry/jerry-core/vm/vm.c:391
    #12 0x812c532 in vm_execute iotjs/deps/jerry/jerry-core/vm/vm.c:2661
    #13 0x812cac8 in vm_run iotjs/deps/jerry/jerry-core/vm/vm.c:2740
    #14 0x80e7291 in ecma_op_function_call iotjs/deps/jerry/jerry-core/ecma/operations/ecma-function-object.c:524
    #15 0x8122370 in opfunc_call iotjs/deps/jerry/jerry-core/vm/vm.c:391
    #16 0x812c532 in vm_execute iotjs/deps/jerry/jerry-core/vm/vm.c:2661
    #17 0x812cac8 in vm_run iotjs/deps/jerry/jerry-core/vm/vm.c:2740
    #18 0x80e7291 in ecma_op_function_call iotjs/deps/jerry/jerry-core/ecma/operations/ecma-function-object.c:524
    #19 0x8122370 in opfunc_call iotjs/deps/jerry/jerry-core/vm/vm.c:391
    #20 0x812c532 in vm_execute iotjs/deps/jerry/jerry-core/vm/vm.c:2661
    #21 0x812cac8 in vm_run iotjs/deps/jerry/jerry-core/vm/vm.c:2740
    #22 0x80e7291 in ecma_op_function_call iotjs/deps/jerry/jerry-core/ecma/operations/ecma-function-object.c:524
    #23 0x8122370 in opfunc_call iotjs/deps/jerry/jerry-core/vm/vm.c:391
    #24 0x812c532 in vm_execute iotjs/deps/jerry/jerry-core/vm/vm.c:2661
    #25 0x812cac8 in vm_run iotjs/deps/jerry/jerry-core/vm/vm.c:2740
    #26 0x80e7291 in ecma_op_function_call iotjs/deps/jerry/jerry-core/ecma/operations/ecma-function-object.c:524
    #27 0x8122370 in opfunc_call iotjs/deps/jerry/jerry-core/vm/vm.c:391
    #28 0x812c532 in vm_execute iotjs/deps/jerry/jerry-core/vm/vm.c:2661
    #29 0x812cac8 in vm_run iotjs/deps/jerry/jerry-core/vm/vm.c:2740

SUMMARY: AddressSanitizer: heap-use-after-free ??:0 ??
Shadow bytes around the buggy address:
  0x3e4204e0: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x3e4204f0: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x3e420500: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x3e420510: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x3e420520: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
=>0x3e420530: fd fd fd fd fd fd fd fd fd fd fd fd fd fd[fd]fd
  0x3e420540: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x3e420550: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x3e420560: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x3e420570: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x3e420580: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
==24507==ABORTING
```

<sup>Found by  [Fuzzinator](http://fuzzinator.readthedocs.io/)</sup>

### PR DESCRIPTION
**Pull request by daeyeon**
This commit fixes the type of offset and of length variables to handle negative length input.

IoT.js-DCO-1.0-Signed-off-by: Daeyeon Jeong daeyeon.jeong@samsung.com

### CODE REVIEW

File: src/module/iotjs_module_fs.c [hunk 1]
```diff
@@ -243,14 +243,14 @@ JHANDLER_FUNCTION(Read) {
 
   int fd = JHANDLER_GET_ARG(0, number);
   const iotjs_jval_t* jbuffer = JHANDLER_GET_ARG(1, object);
-  int offset = JHANDLER_GET_ARG(2, number);
-  int length = JHANDLER_GET_ARG(3, number);
+  size_t offset = JHANDLER_GET_ARG(2, number);
+  size_t length = JHANDLER_GET_ARG(3, number);
```
Comment (glistening) [inline src/module/iotjs_module_fs.c]: I am not sure this change is correct since it silently cast integer to unsigned type, some negative size offset may pass the check, and do unintended operation.

Comment (daeyeon) [inline src/module/iotjs_module_fs.c]: The existing filter-logic below seems ok to check. In case of negative offset on unsigned type, integer underflow will occur. So, the condition, `(offset >= data_length)`, will be true.
```
if (offset >= data_length) {
    JHANDLER_THROW(RANGE, "offset out of bound");
    return;
}
```

Comment (glistening) [inline src/module/iotjs_module_fs.c]: I think the condition `(offset >= data_length)` may be false. For example, on 32-bit architecture, If a user passes `INT_MIN` (-2147483648) to offset, `INT_MIN` will be interpreted as `-INT_MIN` (+2147483648) after casting to size_t. If `data_length` is larger than` -INT_MIN`, the user will read some value at the unintended large offset (It is want I mentioned as unintended operation on above comment). What about checking the sign of offset and throwing exception on negative integer? I think the `length` has the same problem.

Comment (daeyeon) [inline src/module/iotjs_module_fs.c]: I fixed this as discussed. Thank you.

**Comment by yichoi** [comment]
LGTM
