### PR TITLE
Change socket error handling to fix #1078

### LINKED ISSUE #1078: Http request - server unreachable bug
Hello,
I have a problem with http request case when server is unreachable. 
Running test code bellow, doesn't return any error/exception when request is sent to unreachable host.
```
var http = require('http');

var request = http.request({
  host: 'localhost',
  port: 5000,
  path: '/',
  method: 'GET'
}, function (response) {
  response.on('data', function (chunk) {});
  response.on('end', function (chunk) {
    console.log('RESPONSE');
  });
  response.on('error', function (error) {
    console.log('RESPONSE', error);
  });
});
request.on('error', function (error) {
  console.log('REQUEST', error);
});
request.end();
```
Commenting the last line, hides(removes?) bug and example works properly. However, if I understand correctly API reference, this line is mandatory.

### PR DESCRIPTION
**Pull request by akhilkedia**
Fixes #1078 

If net module's socket errors, the pending writes are never finished, and as such the socket 'close' event is never fired. Since HTTPClient depends on the close event to fire its on error event if the request could not be started, this error event was actually never fired.

This patch fixes the above by making net module's socket "pretend" to write everything in its stream buffer and calls end so that the socket can call close as expected by the HTTPClient class.

This same approach is also used currently in the HTTPS module to handle this very case. Please feel free to suggest alternative ways of fixing this if there is a better way.

The older test case seems to have intentionally waited before calling request.end in an attempt to bypass this issue. Removed that wait.

IoT.js-DCO-1.0-Signed-off-by: Akhil Kedia akhil.kedia@samsung.com

### CODE REVIEW

File: src/js/net.js [hunk 1]
```diff
@@ -150,16 +150,27 @@ Socket.prototype._write = function(chunk, callback, afterWrite) {
...
   var self = this;
 
-  resetSocketTimeout(self);
-
-  self._handle.owner = self;
-
-  self._handle.write(chunk, function(status) {
-    afterWrite(status);
+  if (self.errored) {
+    console.log('About to setTimeout for afterwrite');
```
Comment (kolipka) [inline src/js/net.js]: Please remove console.log

File: src/js/net.js [hunk 2]
```diff
@@ -150,16 +150,27 @@ Socket.prototype._write = function(chunk, callback, afterWrite) {
...
+    process.nextTick(afterWrite, 1);
     if (util.isFunction(callback)) {
-      callback.call(self, status);
+      console.log('About to setTimeout for callback');
```
Comment (zherczeg) [inline src/js/net.js]: Please remove this condol.log as well.

File: src/js/net.js (hunk 1 above)
Comment (akhilkedia) [inline src/js/net.js]: Oops. Will fix.

File: src/js/net.js (hunk 2 above)
Comment (akhilkedia) [inline src/js/net.js]: Will fix.

**Comment by yichoi** [comment]
LGTM
