### PR TITLE
Check JS side if process.exit gets a wrong argument type

### LINKED ISSUE #1348: Assertion 'jerry_value_is_number(jexitcode)' failed in iotjs_process_exitcode
###### IoT.js version:

```
Checked revision: a6b2d75
Build command: tools/build.py --buildtype debug --no-snapshot --no-check-test
```
###### OS:

```
Ubuntu 17.10
```
###### Test case:

```javascript
process.on('uncaughtException', function(err) { } );
process.exit('callback');
```

###### Backtrace:

```
iotjs/src/iotjs_binding_helper.c:137: Assertion 'jerry_value_is_number(jexitcode)' failed.
Breakpoint 1, iotjs_process_exitcode () at iotjs/src/iotjs_binding_helper.c:137
137	  IOTJS_ASSERT(jerry_value_is_number(jexitcode));
(gdb) bt
#0  iotjs_process_exitcode () at iotjs/src/iotjs_binding_helper.c:137
#1  0x000055555556ca6f in iotjs_start (env=0x55555584a440 <current_env>) at iotjs/src/iotjs.c:160
#2  0x000055555556cce8 in iotjs_entry (argc=2, argv=0x7fffffffdec8) at iotjs/src/iotjs.c:218
#3  0x000055555556c4ca in main (argc=2, argv=0x7fffffffdec8) at iotjs/iotjs_linux.c:19
```

<sup>Found by [Fuzzinator](http://fuzzinator.readthedocs.io/) with [grammarinator](https://github.com/renatahodovan/grammarinator)</sup>

### PR DESCRIPTION
**Pull request by DanielBallaSZTE**
Fixes #1348

IoT.js-DCO-1.0-Signed-off-by: Daniel Balla dballa@inf.u-szeged.hu

### CODE REVIEW

File: src/js/iotjs.js [hunk 1]
```diff
@@ -138,6 +138,9 @@
   process.exitCode = 0;
   process._exiting = false;
   process.emitExit = function(code) {
+    if (typeof(code) !== 'number') {
```
Comment (daeyeon) [inline src/js/iotjs.js]: Using `util.isNumber` for this seems our implicit convention.

Comment (daeyeon) [inline src/js/iotjs.js]: I suggest using `typeof` without the bracket pair. `typeof code`.

Comment (DanielBallaSZTE) [reply src/js/iotjs.js]: You are right, that's more JS like.
Thank you !
